/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const HomePageIndexLazyRouteImport = createFileRoute('/home-page/')()

const HomePageIndexLazyRoute = HomePageIndexLazyRouteImport.update({
  id: '/home-page/',
  path: '/home-page/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/home-page/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/home-page/': typeof HomePageIndexLazyRoute
}
export interface FileRoutesByTo {
  '/home-page': typeof HomePageIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home-page/': typeof HomePageIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home-page/'
  fileRoutesByTo: FileRoutesByTo
  to: '/home-page'
  id: '__root__' | '/home-page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomePageIndexLazyRoute: typeof HomePageIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home-page/': {
      id: '/home-page/'
      path: '/home-page'
      fullPath: '/home-page/'
      preLoaderRoute: typeof HomePageIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomePageIndexLazyRoute: HomePageIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
